{{- if not .Values.global.ingress.only }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-agent-config
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "edj-vmw.labels" . | nindent 4 }}
data:
{{- range .Files.Lines .Values.app.configFile }}
{{ . | indent 2 }}
{{- end }}
{{- end }}
